Bump MSL version for multiview to 21
Bumped version from 12 to 21, as required by visionOS:
error: 'render_target_array_index' attribute requires Metal language standard ios-metal2.1 or higher
    uint gl_Layer [[render_target_array_index]];

Task-number: QTBUG-126294
Pick-to: 6.8
Change-Id: I14c2c2cbfa19a3a19b2dc8bfa1626fb29657c72e
Reviewed-by: Laszlo Agocs <laszlo.agocs@qt.io>